config/routes.rb
Rails.application.routes.draw do
  resources :roles
  devise_scope :user do
    # Redirests signing out users back to sign-in
    get "users", to: "devise/sessions#new"
  end

  devise_for :users

  root "home#index"

  get "/api/data", to: "api#data"
  get "/api/login", to: "api#login"
  get "/api/all_users", to: "api#all_users"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :users

  def admin?
    Role.where(name: admin).first
  end
end

app/models/user.rb
class User < ApplicationRecord

  before_create :set_default_role
  belongs_to :role, optional: true

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def is_admin?
    role && role.id==1
  end

  private

  def set_default_role
    puts " >>>>>>> finding the role now"
    self.role ||= Role.find_by(name: "technician")
  end
end

app/controllers/api_controller.rb
class ApiController < ApplicationController


  def data

    render json: { user: "Nmuta" }.to_json
  end

  def login
    puts "here are my params "+params['jina']
    puts "here are my params "+params['urfunguzo']

    jina = params['jina']
    urfunguzo = params['urfunguzo'];

    usr = User.find_by(email: params[:jina])
    if usr && usr.valid_password?(params['urfunguzo']) && usr.role
      user_role = usr.role.name
      render json: { user: usr.email, role:user_role}.to_json
    else
      render json: { user: "error", role: "error"}.to_json
    end
  end

  def all_users
    users = User.all
    mapped_users = users.map{|user| {email: user.email, id: user.id,
                                     role: user.role.name, created_at: user.created_at,
                                     updated_at: user.updated_at}}
    render json: { users: mapped_users }.to_json
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :set_role, only: %i[ show edit update destroy ]

  # GET /roles or /roles.json
  def index
    @roles = Role.all
  end

  # GET /roles/1 or /roles/1.json
  def show
  end

  # GET /roles/new
  def new
    @role = Role.new
  end

  # GET /roles/1/edit
  def edit
  end

  # POST /roles or /roles.json
  def create
    @role = Role.new(role_params)

    respond_to do |format|
      if @role.save
        format.html { redirect_to role_url(@role), notice: "Role was successfully created." }
        format.json { render :show, status: :created, location: @role }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roles/1 or /roles/1.json
  def update
    respond_to do |format|
      if @role.update(role_params)
        format.html { redirect_to role_url(@role), notice: "Role was successfully updated." }
        format.json { render :show, status: :ok, location: @role }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1 or /roles/1.json
  def destroy
    @role.destroy

    respond_to do |format|
      format.html { redirect_to roles_url, notice: "Role was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_role
      @role = Role.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def role_params
      params.require(:role).permit(:name)
    end
end

app/controllers/turbo_devise_controller.rb
class TurboDeviseController < ApplicationController
  class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
    rescue ActionView::MissingTemplate => error
      if get?
        raise error
      elsif has_errors? && default_action
        render rendering_options.merge(formats: :html, status: :unprocessable_entity)
      else
        redirect_to navigation_location
      end
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/home/index.html.erb
    <% if current_user %>

      <br>
      <% if current_user && current_user.role == Role.first %>
       <div class="user_administration">
         <p>
           Administer users:
         </p>
         <table class="formatted_table">
           <thead>
           <th>Email</th>
           <th>Role</th>
           </tr>
           </thead>
           <tbody>
           <% User.all.each do |user| %>
             <tr>
               <td><%= user.email %></td>
               <td><%= user.role.name %></td>
             </tr>
           <% end %>
           </tbody>
         </table>

       </div>


      <% else  %>
        Welcome, <%= current_user.email %>

      <% end %>

      <div class="logout_buton_container">

      <%= button_to "logout", destroy_user_session_path, method: :delete  %>
        <br>
      </div>
    <% end %>

    <% if !current_user %>
      <%= button_to "login or sign up", new_user_session_path, method: :get  %>
    <% end %>

 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails7DeviseDemo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>



    <%= javascript_importmap_tags %>
  </head>

  <body>

    <div class="login_container">
        <% if notice %>
          <p class="alert alert-success"><%= notice %></p>
        <% end %>
        <% if alert %>
          <p class="alert alert-danger"><%= alert %></p>
        <% end %>
        <%= yield %>
    </div>
  </body>
</html>

app/views/roles/_form.html.erb
<%= form_with(model: role) do |form| %>
  <% if role.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(role.errors.count, "error") %> prohibited this role from being saved:</h2>

      <ul>
        <% role.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/roles/_role.html.erb
<div id="<%= dom_id role %>">
  <p>
    <strong>Name:</strong>
    <%= role.name %>
  </p>

</div>

app/views/roles/edit.html.erb
<h1>Editing role</h1>

<%= render "form", role: @role %>

<br>

<div>
  <%= link_to "Show this role", @role %> |
  <%= link_to "Back to roles", roles_path %>
</div>

app/views/roles/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Roles</h1>

<div id="roles">
  <% @roles.each do |role| %>
    <%= render role %>
    <p>
      <%= link_to "Show this role", role %>
    </p>
  <% end %>
</div>

<%= link_to "New role", new_role_path %>

app/views/roles/new.html.erb
<h1>New role</h1>

<%= render "form", role: @role %>

<br>

<div>
  <%= link_to "Back to roles", roles_path %>
</div>

app/views/roles/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @role %>

<div>
  <%= link_to "Edit this role", edit_role_path(@role) %> |
  <%= link_to "Back to roles", roles_path %>

  <%= button_to "Destroy this role", @role, method: :delete %>
</div>